#version: '3.8'

services:
  # PostgreSQL Database with pgvector extension
  postgres:
    image: pgvector/pgvector:pg15
    container_name: insights_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-insights}
      POSTGRES_USER: ${POSTGRES_USER:-insights_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-insights_pass}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./insights-api/scripts/init-pgvector.sql:/docker-entrypoint-initdb.d/01-init-pgvector.sql
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-insights_user} -d ${POSTGRES_DB:-insights}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - insights_network

  # Redis Cache & Queue
  redis:
    image: redis:7-alpine
    container_name: insights_redis
    command: redis-server --appendonly yes --maxmemory 512mb --maxmemory-policy allkeys-lru
    volumes:
      - redis_data:/data
    ports:
      - "${REDIS_PORT:-6379}:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - insights_network

  # Main FastAPI Application
  api:
    build:
      context: .
      target: ${BUILD_TARGET:-development}
    container_name: insights_api
    environment:
      - ENV=${ENV:-dev}
      - DEBUG=${DEBUG:-true}
      - DB_URL=postgresql+asyncpg://${POSTGRES_USER:-insights_user}:${POSTGRES_PASSWORD:-insights_pass}@postgres:5432/${POSTGRES_DB:-insights}
      - REDIS_URL=redis://redis:6379/0
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - ARQ_REDIS_URL=redis://redis:6379/
      - JWT_SECRET_KEY=${JWT_SECRET_KEY:-your-super-secret-jwt-key-change-this-in-production}
      - CORS_ORIGINS=${CORS_ORIGINS:-http://localhost:5173,http://127.0.0.1:5173,http://localhost:3000,http://127.0.0.1:3000}
    volumes:
      - ./insights-api/app:/app/app
      - ./insights-api/tests:/app/tests
      - ./insights-api/scripts:/app/scripts
      - ./logs:/app/logs
      - ./insights-api/pyproject.toml:/app/pyproject.toml
      - ./README.md:/app/README.md
    ports:
      - "${API_PORT:-8000}:8000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - insights_network
    restart: unless-stopped

  # ARQ Worker for Background Jobs
  worker:
    build:
      context: .
      target: ${BUILD_TARGET:-development}
    container_name: insights_worker
    command: /app/.venv/bin/arq app.workers.scheduler.WorkerSettings
    environment:
      - ENV=${ENV:-dev}
      - DEBUG=${DEBUG:-true}
      - DB_URL=postgresql+asyncpg://${POSTGRES_USER:-insights_user}:${POSTGRES_PASSWORD:-insights_pass}@postgres:5432/${POSTGRES_DB:-insights}
      - REDIS_URL=redis://redis:6379/0
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - ARQ_REDIS_URL=redis://redis:6379/
    volumes:
      - ./insights-api/app:/app/app
      - ./insights-api/tests:/app/tests
      - ./insights-api/scripts:/app/scripts
      - ./logs:/app/logs
      - ./insights-api/pyproject.toml:/app/pyproject.toml
      - ./README.md:/app/README.md
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - insights_network
    restart: unless-stopped

  # Frontend Vite dev server
  frontend:
    image: node:20-alpine
    container_name: insights_frontend
    working_dir: /app/insights-front
    command: sh -c "npm ci && npm run dev -- --host 0.0.0.0 --port 5173"
    ports:
      - "5173:5173"
    volumes:
      - ./insights-front:/app/insights-front
      - /app/insights-front/node_modules
    env_file:
      - .env.docker
    depends_on:
      - api
    networks:
      - insights_network

  # Redis Commander - Redis GUI
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: insights_redis_commander
    environment:
      - REDIS_HOSTS=local:redis:6379
      - HTTP_USER=${REDIS_COMMANDER_USER:-admin}
      - HTTP_PASSWORD=${REDIS_COMMANDER_PASSWORD:-admin}
    ports:
      - "${REDIS_COMMANDER_PORT:-8081}:8081"
    depends_on:
      - redis
    networks:
      - insights_network

  # pgAdmin - PostgreSQL GUI
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: insights_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@insights.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT:-8080}:80"
    depends_on:
      - postgres
    networks:
      - insights_network

  # ARQ Monitor - Web UI for monitoring ARQ tasks
  arq-monitor:
    image: antonk0/arq-ui:latest
    container_name: insights_arq_monitor
    restart: unless-stopped
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - QUEUE_NAME=arq:queue
      - PYTHONPATH=/app
    volumes:
      - ./insights-api/app:/app/app
    ports:
      - "${ARQ_MONITOR_PORT:-8082}:8000"
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - insights_network
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/arq/ui'); print('OK')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  postgres_data:
  redis_data:
  pgadmin_data:

networks:
  insights_network:
    driver: bridge